In [1]:
import read_geolife
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import KFold

c:\Tensorflow\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df = read_geolife.read_all_users("Data")
df

[1/182] processing user 000
[2/182] processing user 001
[3/182] processing user 002
[4/182] processing user 003
[5/182] processing user 004
[6/182] processing user 005
[7/182] processing user 006
[8/182] processing user 007
[9/182] processing user 008
[10/182] processing user 009
[11/182] processing user 010


c:\Users\김진수\Desktop\geolife\read_geolife.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  points['label'][no_label] = 0


[12/182] processing user 011
[13/182] processing user 012
[14/182] processing user 013
[15/182] processing user 014
[16/182] processing user 015
[17/182] processing user 016
[18/182] processing user 017
[19/182] processing user 018
[20/182] processing user 019
[21/182] processing user 020
[22/182] processing user 021
[23/182] processing user 022
[24/182] processing user 023
[25/182] processing user 024
[26/182] processing user 025
[27/182] processing user 026
[28/182] processing user 027
[29/182] processing user 028
[30/182] processing user 029
[31/182] processing user 030
[32/182] processing user 031
[33/182] processing user 032
[34/182] processing user 033
[35/182] processing user 034
[36/182] processing user 035
[37/182] processing user 036
[38/182] processing user 037
[39/182] processing user 038
[40/182] processing user 039
[41/182] processing user 040
[42/182] processing user 041
[43/182] processing user 042
[44/182] processing user 043
[45/182] processing user 044
[46/182] proce

time        lat         lon          alt  label  user
0  2008-10-23 02:53:04  39.984702  116.318417   492.000000      0     0
1  2008-10-23 02:53:10  39.984683  116.318450   492.000000      0     0
2  2008-10-23 02:53:15  39.984686  116.318417   492.000000      0     0
3  2008-10-23 02:53:20  39.984688  116.318385   492.000000      0     0
4  2008-10-23 02:53:25  39.984655  116.318263   492.000000      0     0
..                 ...        ...         ...          ...    ...   ...
17 2008-03-14 03:39:56  40.914867  111.710500  3802.493438      0   181
18 2008-03-14 03:41:17  40.914267  111.710333  3795.931759      0   181
19 2008-03-14 03:43:02  40.912467  111.710667  3795.931759      0   181
20 2008-03-14 03:43:28  40.911517  111.711317  3779.527559      0   181
21 2008-03-14 03:43:40  40.910933  111.711617  3802.493438      0   181

[24876978 rows x 6 columns]

In [112]:
df.time = df.time.apply(lambda x : time.mktime(x.to_pydatetime().timetuple()))
df.to_pickle("geolife.pkl")

time        lat         lon    alt  label  user
1    1.206684e+09  39.894178  116.318200 -777.0      6    10
2    1.206684e+09  39.894505  116.321132 -777.0      6    10
3    1.206684e+09  39.894953  116.326452 -777.0      6    10
4    1.206684e+09  39.894600  116.332542 -777.0      6    10
5    1.206684e+09  39.889622  116.337040 -777.0      6    10
..            ...        ...         ...    ...    ...   ...
655  1.227893e+09  40.029529  116.411977  291.0      5   179
656  1.227893e+09  40.029320  116.411975  289.0      5   179
657  1.227893e+09  40.029111  116.411963  275.0      5   179
658  1.227893e+09  40.028904  116.411962  274.0      5   179
659  1.227893e+09  40.028697  116.411961  274.0      5   179

[5427117 rows x 6 columns]

time        lat         lon          alt  label  user
0   1.224698e+09  39.984702  116.318417   492.000000      0     0
1   1.224698e+09  39.984683  116.318450   492.000000      0     0
2   1.224698e+09  39.984686  116.318417   492.000000      0     0
3   1.224698e+09  39.984688  116.318385   492.000000      0     0
4   1.224698e+09  39.984655  116.318263   492.000000      0     0
..           ...        ...         ...          ...    ...   ...
17  1.205434e+09  40.914867  111.710500  3802.493438      0   181
18  1.205434e+09  40.914267  111.710333  3795.931759      0   181
19  1.205434e+09  40.912467  111.710667  3795.931759      0   181
20  1.205434e+09  40.911517  111.711317  3779.527559      0   181
21  1.205434e+09  40.910933  111.711617  3802.493438      0   181

[19449861 rows x 6 columns]

## Load

In [4]:
import pandas as pd
df = pd.read_pickle("geolife.pkl")
df

time        lat         lon          alt  label  user
0   1.224698e+09  39.984702  116.318417   492.000000      0     0
1   1.224698e+09  39.984683  116.318450   492.000000      0     0
2   1.224698e+09  39.984686  116.318417   492.000000      0     0
3   1.224698e+09  39.984688  116.318385   492.000000      0     0
4   1.224698e+09  39.984655  116.318263   492.000000      0     0
..           ...        ...         ...          ...    ...   ...
17  1.205434e+09  40.914867  111.710500  3802.493438      0   181
18  1.205434e+09  40.914267  111.710333  3795.931759      0   181
19  1.205434e+09  40.912467  111.710667  3795.931759      0   181
20  1.205434e+09  40.911517  111.711317  3779.527559      0   181
21  1.205434e+09  40.910933  111.711617  3802.493438      0   181

[24876978 rows x 6 columns]

In [59]:
df["prevlat"] = df.lat.shift(1)
df["prevlon"] = df.lon.shift(1)
df["prevalt"] = df.alt.shift(1)
df["prevtime"] = df.time.shift(1)
df = df.fillna(0)
df["v"] = abs((df.lat-df.prevlat)+(df.lon-df.prevlon)+(df.alt-df.prevalt))/(df.time-df.prevtime+1e-9)
df

time        lat         lon          alt  label  user    prevlat  \
0   1.224698e+09  39.984702  116.318417   492.000000      0     0   0.000000   
1   1.224698e+09  39.984683  116.318450   492.000000      0     0  39.984702   
2   1.224698e+09  39.984686  116.318417   492.000000      0     0  39.984683   
3   1.224698e+09  39.984688  116.318385   492.000000      0     0  39.984686   
4   1.224698e+09  39.984655  116.318263   492.000000      0     0  39.984688   
..           ...        ...         ...          ...    ...   ...        ...   
17  1.205434e+09  40.914867  111.710500  3802.493438      0   181  40.915433   
18  1.205434e+09  40.914267  111.710333  3795.931759      0   181  40.914867   
19  1.205434e+09  40.912467  111.710667  3795.931759      0   181  40.914267   
20  1.205434e+09  40.911517  111.711317  3779.527559      0   181  40.912467   
21  1.205434e+09  40.910933  111.711617  3802.493438      0   181  40.911517   

       prevlon      prevalt      prevtime             v  
0     0.000000     0.000000  0.000000e+00  5.293575e-07  
1   116.318417   492.000000  1.224698e+09  2.333333e-06  
2   116.318450   492.000000  1.224698e+09  6.000000e-06  
3   116.318417   492.000000  1.224698e+09  6.000000e-06  
4   116.318385   492.000000  1.224698e+09  3.100000e-05  
..         ...          ...           ...           ...  
17  111.711450  3841.863517  1.205433e+09  3.515321e-01  
18  111.710500  3802.493438  1.205434e+09  8.101786e-02  
19  111.710333  3795.931759  1.205434e+09  1.396825e-05  
20  111.710667  3795.931759  1.205434e+09  6.309423e-01  
21  111.711317  3779.527559  1.205434e+09  1.913800e+00  

[24876978 rows x 11 columns]

In [60]:
train_data = df[df.label!=0]
test_data = df[df.label==0]
display(train_data)
display(test_data)

time        lat         lon    alt  label  user    prevlat  \
1    1.206684e+09  39.894178  116.318200 -777.0      6    10  39.893397   
2    1.206684e+09  39.894505  116.321132 -777.0      6    10  39.894178   
3    1.206684e+09  39.894953  116.326452 -777.0      6    10  39.894505   
4    1.206684e+09  39.894600  116.332542 -777.0      6    10  39.894953   
5    1.206684e+09  39.889622  116.337040 -777.0      6    10  39.894600   
..            ...        ...         ...    ...    ...   ...        ...   
655  1.227893e+09  40.029529  116.411977  291.0      5   179  40.029739   
656  1.227893e+09  40.029320  116.411975  289.0      5   179  40.029529   
657  1.227893e+09  40.029111  116.411963  275.0      5   179  40.029320   
658  1.227893e+09  40.028904  116.411962  274.0      5   179  40.029111   
659  1.227893e+09  40.028697  116.411961  274.0      5   179  40.028904   

        prevlon  prevalt      prevtime         v  
1    116.313677   -777.0  1.206683e+09  0.000014  
2    116.318200   -777.0  1.206684e+09  0.000096  
3    116.321132   -777.0  1.206684e+09  0.000098  
4    116.326452   -777.0  1.206684e+09  0.000097  
5    116.332542   -777.0  1.206684e+09  0.000008  
..          ...      ...           ...       ...  
655  116.411980    294.0  1.227893e+09  1.500106  
656  116.411977    291.0  1.227893e+09  1.000105  
657  116.411975    289.0  1.227893e+09  7.000110  
658  116.411963    275.0  1.227893e+09  0.500104  
659  116.411962    274.0  1.227893e+09  0.000104  

[5427117 rows x 11 columns]

time        lat         lon          alt  label  user    prevlat  \
0   1.224698e+09  39.984702  116.318417   492.000000      0     0   0.000000   
1   1.224698e+09  39.984683  116.318450   492.000000      0     0  39.984702   
2   1.224698e+09  39.984686  116.318417   492.000000      0     0  39.984683   
3   1.224698e+09  39.984688  116.318385   492.000000      0     0  39.984686   
4   1.224698e+09  39.984655  116.318263   492.000000      0     0  39.984688   
..           ...        ...         ...          ...    ...   ...        ...   
17  1.205434e+09  40.914867  111.710500  3802.493438      0   181  40.915433   
18  1.205434e+09  40.914267  111.710333  3795.931759      0   181  40.914867   
19  1.205434e+09  40.912467  111.710667  3795.931759      0   181  40.914267   
20  1.205434e+09  40.911517  111.711317  3779.527559      0   181  40.912467   
21  1.205434e+09  40.910933  111.711617  3802.493438      0   181  40.911517   

       prevlon      prevalt      prevtime             v  
0     0.000000     0.000000  0.000000e+00  5.293575e-07  
1   116.318417   492.000000  1.224698e+09  2.333333e-06  
2   116.318450   492.000000  1.224698e+09  6.000000e-06  
3   116.318417   492.000000  1.224698e+09  6.000000e-06  
4   116.318385   492.000000  1.224698e+09  3.100000e-05  
..         ...          ...           ...           ...  
17  111.711450  3841.863517  1.205433e+09  3.515321e-01  
18  111.710500  3802.493438  1.205434e+09  8.101786e-02  
19  111.710333  3795.931759  1.205434e+09  1.396825e-05  
20  111.710667  3795.931759  1.205434e+09  6.309423e-01  
21  111.711317  3779.527559  1.205434e+09  1.913800e+00  

[19449861 rows x 11 columns]

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(train_data[["time","lat","lon","alt","user","v"]],train_data.label, shuffle=False)
X_test = test_data[["time", "lat","lon","alt","v"]]
display(X_train)
display(y_train)

time        lat         lon          alt  user         v
1    1.206684e+09  39.894178  116.318200  -777.000000    10  0.000014
2    1.206684e+09  39.894505  116.321132  -777.000000    10  0.000096
3    1.206684e+09  39.894953  116.326452  -777.000000    10  0.000098
4    1.206684e+09  39.894600  116.332542  -777.000000    10  0.000097
5    1.206684e+09  39.889622  116.337040  -777.000000    10  0.000008
..            ...        ...         ...          ...   ...       ...
161  1.188886e+09  34.247367  108.931217  1450.131234   139  0.000225
162  1.188886e+09  34.247800  108.931300  1450.131234   139  0.000027
163  1.188886e+09  34.248383  108.930550  1450.131234   139  0.000006
164  1.188886e+09  34.247350  108.929700  1450.131234   139  0.000209
165  1.188886e+09  34.248567  108.929467  1407.480315   139  2.665621

[4070337 rows x 6 columns]

1       6
2       6
3       6
4       6
5       6
       ..
161    11
162    11
163    11
164    11
165    11
Name: label, Length: 4070337, dtype: int64

## 랜덤포레스트

In [63]:
rf_classifier = RandomForestClassifier(n_estimators = 18)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=18,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [64]:
display(rf_classifier.score(X_train, y_train))
display(rf_classifier.score(X_valid,y_valid))
display(rf_classifier.predict(X_valid))

0.9999540578581085

0.35120432199767093

array([11, 11, 11, ...,  1,  4,  4], dtype=int64)

In [109]:
rf_classifier.predict(X_test)

array([11, 11, 11, ...,  4,  4,  4], dtype=int64)

## LogisticRegression

In [110]:
logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [111]:
display(logreg_classifier.score(X_train,y_train))
display(logreg_classifier.score(X_valid,y_valid))
display(logreg_classifier.predict(X_test))

0.2921259345356416

0.2921254735476643

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)